### ISSUE TITLE
FR: TypeScript type definitions

### ISSUE THREAD

**Issue by merlinnot** [googleapis/nodejs-iot#199] opened 2019-09-04 12:11 UTC
**Is your feature request related to a problem? Please describe.**

Developer experience would be much better if this package would provide TypeScript type definitions.

 **Describe the solution you'd like**

Provide full and correct TypeScript type definitions.

 **Describe alternatives you've considered**

Writing type definitions myself.

 **Additional context**

None.

**Comment by callmehiphop** [comment] 2019-09-04 15:43
👋 @merlinnot this is definitely on our radar, currently the team is busy at work writing a new code generator that will provide types for all our generated clients, including this one.

I'm going to close this as a duplicate of https://github.com/googleapis/google-cloud-node/issues/952.

**Closed by callmehiphop** 2019-09-04 15:43 UTC
Labels: type: feature request
